services:
  - type: web
    name: pdf-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --timeout 300 --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: OPENAI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
    disk:
      name: pdf-storage
      mountPath: /opt/render/project/src/uploads
      sizeGB: 10

